"""
Shared pytest fixtures and constants for pyGeneBasis tests.

All numerical correctness tests compare Python outputs to R reference outputs
generated by ``generate_r_reference.R``.  If the reference data is not yet
present (the R script hasn't been run), the relevant fixtures skip automatically.

Reference data layout
---------------------
tests/reference_data/
    mouse_embryo/
        counts.mtx          logcounts matrix (genes × cells)
        obs.csv             cell metadata
        var.csv             gene names
        r_outputs/          one CSV per geneBasisR function output
    bg_sn/
        (same structure)

Tolerance constants
-------------------
Defined here and imported by test modules.  Matches the values in DEVELOPMENT.md.
"""

from __future__ import annotations

from pathlib import Path

import anndata as ad
import numpy as np
import pandas as pd
import pytest
import scipy.io
import scipy.sparse

from helpers import (  # noqa: F401 — re-exported for convenience
    SPEARMAN_TOL, MAE_TOL, GENE_OVERLAP_EXACT, GENE_OVERLAP_APPROX,
    KNN_OVERLAP_TOL, CT_AGREEMENT_TOL,
    N_NEIGHBORS, N_PCS_ALL, P_MINKOWSKI, N_GENES, RANDOM_STATE,
    SEED_GENES_MOUSE, SEED_GENES_BG_SN,
    overlap_fraction, knn_overlap, knn_jaccard, weighted_overlap_fraction,
    spearman_r,
)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REF_DIR   = Path(__file__).parent / "reference_data"
MOUSE_DIR = REF_DIR / "mouse_embryo"
BG_SN_DIR = REF_DIR / "bg_sn"


# ---------------------------------------------------------------------------
# Reference data loaders
# ---------------------------------------------------------------------------

def _load_adata(dataset_dir: Path) -> ad.AnnData:
    """Load a reference dataset as AnnData from MTX + CSV files."""
    if not dataset_dir.exists():
        pytest.skip(
            f"Reference data not found: {dataset_dir}\n"
            "Run generate_r_reference.R first:\n"
            "  pixi run -e r-genebasis Rscript "
            "software/geneBasis/pyGeneBasis/tests/generate_r_reference.R"
        )
    counts = scipy.io.mmread(dataset_dir / "counts.mtx")
    # MTX from R is always written genes×cells; transpose to cells×genes for AnnData
    counts = scipy.sparse.csr_matrix(counts.T)
    obs = pd.read_csv(dataset_dir / "obs.csv", index_col=0)
    var = pd.read_csv(dataset_dir / "var.csv", index_col=0)
    adata = ad.AnnData(X=counts, obs=obs, var=var)
    return adata


def _load_r_outputs(dataset_dir: Path) -> dict[str, pd.DataFrame]:
    """Load all R reference CSVs as a name → DataFrame dict."""
    rout = dataset_dir / "r_outputs"
    if not rout.exists():
        pytest.skip(
            f"R outputs not found: {rout}\n"
            "Run generate_r_reference.R first."
        )
    def _load_one(f):
        # R writes row names as an unnamed first column ("","V1","V2",...).
        # Detect this and set index_col=0 only for those files so that .values
        # gives the numeric data without the row-name string column.
        with open(f) as fh:
            first_col = fh.readline().split(",")[0].strip('"')
        return pd.read_csv(f, index_col=0 if first_col == "" else None)

    return {f.stem: _load_one(f) for f in sorted(rout.glob("*.csv"))}


def overlap_fraction(a: list | np.ndarray, b: list | np.ndarray) -> float:
    """Fraction of elements in a that appear in b."""
    return len(set(a) & set(b)) / len(set(a))


def knn_overlap(idx_a: np.ndarray, idx_b: np.ndarray) -> float:
    """Mean per-row fraction of neighbours in common between two index matrices."""
    fracs = [
        len(set(row_a) & set(row_b)) / len(row_a)
        for row_a, row_b in zip(idx_a, idx_b)
    ]
    return float(np.mean(fracs))


def spearman_r(a: np.ndarray, b: np.ndarray) -> float:
    """Spearman rank correlation between two 1-D arrays."""
    from scipy.stats import spearmanr
    return float(spearmanr(a, b).statistic)


# ---------------------------------------------------------------------------
# Dataset fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def adata_mouse() -> ad.AnnData:
    """Mouse embryo E8.5 AnnData (session-scoped — loaded once per test run)."""
    return _load_adata(MOUSE_DIR)


@pytest.fixture(scope="session")
def r_mouse() -> dict[str, pd.DataFrame]:
    """R reference outputs for the mouse embryo dataset."""
    return _load_r_outputs(MOUSE_DIR)


@pytest.fixture(scope="session")
def adata_bg_sn() -> ad.AnnData:
    """BG substantia nigra AnnData (subsampled)."""
    return _load_adata(BG_SN_DIR)


@pytest.fixture(scope="session")
def r_bg_sn() -> dict[str, pd.DataFrame]:
    """R reference outputs for the BG SN dataset."""
    return _load_r_outputs(BG_SN_DIR)


GENE_SEARCH_N_TYPES   = 5   # number of cell types in gene_search_adata
GENE_SEARCH_N_MARKERS = 5   # marker genes per type (25 informative out of 200)


@pytest.fixture(scope="session")
def gene_search_adata() -> ad.AnnData:
    """Synthetic AnnData designed to stress-test gene_search and retain_informative_genes.

    Design goals (addressing limitations of small_adata):
    - 5 cell types instead of 3 — more complex class structure
    - Only 25 informative genes (5 per type, interleaved: type t → genes t, t+5, ...,
      t+20), out of 200 total — most genes are pure noise
    - High SNR: in-class expression Poisson(λ=20→12), background Poisson(λ=0.1) —
      a ~100× contrast makes the informative set unmistakable for HVG selection
    - Decreasing marker strength (20→12) gives a clear preference ordering within
      each type so that gene_search has a steep score landscape for the first ~5
      selections per type, then drops off sharply into noise

    The 25 informative gene indices are 0..24 (interleaved by cell type).
    Genes 25..199 are pure Poisson(0.1) noise.
    """
    rng = np.random.default_rng(7)
    n_types = GENE_SEARCH_N_TYPES
    n_markers = GENE_SEARCH_N_MARKERS
    n_cells_per_type = 50
    n_genes = 200

    cell_types = [f"Type{chr(65+t)}" for t in range(n_types)]  # TypeA .. TypeE
    labels = np.repeat(cell_types, n_cells_per_type)
    n_cells = n_cells_per_type * n_types

    # Background: very low expression so noise genes are easy to distinguish
    counts = rng.poisson(lam=0.1, size=(n_cells, n_genes)).astype(np.float32)

    # Interleaved markers: type t gets genes t, t+n_types, t+2*n_types, ...
    # Decreasing lambdas give a clear greedy preference ordering.
    lams = np.linspace(20.0, 12.0, n_markers)
    for t, ct in enumerate(cell_types):
        marker_cols = list(range(t, t + n_markers * n_types, n_types))
        cell_rows = np.where(labels == ct)[0]
        for j, col in enumerate(marker_cols):
            counts[np.ix_(cell_rows, [col])] = (
                rng.poisson(lam=lams[j], size=(n_cells_per_type, 1)).astype(np.float32)
            )

    counts = np.log1p(counts)

    obs = pd.DataFrame(
        {
            "celltype": labels,
            "batch": rng.choice(["batch1", "batch2"], size=n_cells),
        },
        index=[f"cell_{i}" for i in range(n_cells)],
    )
    var = pd.DataFrame(index=[f"gene_{i}" for i in range(n_genes)])
    return ad.AnnData(X=scipy.sparse.csr_matrix(counts), obs=obs, var=var)


@pytest.fixture(scope="session")
def hierarchical_adata() -> ad.AnnData:
    """Synthetic AnnData with a 2-level cell type hierarchy.

    Hierarchy (class_label → celltype):
        ClassA → TypeA, TypeB
        ClassB → TypeC, TypeD
        ClassC → TypeE          (single-child: constrained_accuracy trivially = 1.0)

    Structure:
        40 cells per type, 200 cells total.
        50 marker genes (10 per type, interleaved) + 50 noise genes = 100 genes.
        Type t (0-indexed) has markers at columns t, t+5, t+10, ..., t+45.
    """
    rng = np.random.default_rng(99)
    n_types          = 5
    n_cells_per_type = 40
    n_markers        = 10
    n_noise          = 50
    n_genes          = n_markers * n_types + n_noise  # 100

    cell_types = ["TypeA", "TypeB", "TypeC", "TypeD", "TypeE"]
    class_map  = {
        "TypeA": "ClassA", "TypeB": "ClassA",
        "TypeC": "ClassB", "TypeD": "ClassB",
        "TypeE": "ClassC",
    }

    labels  = np.repeat(cell_types, n_cells_per_type)
    n_cells = n_cells_per_type * n_types

    counts = rng.poisson(lam=0.1, size=(n_cells, n_genes)).astype(np.float32)
    for t, ct in enumerate(cell_types):
        marker_cols = list(range(t, t + n_markers * n_types, n_types))
        cell_rows   = np.where(labels == ct)[0]
        counts[np.ix_(cell_rows, marker_cols)] = rng.poisson(
            lam=15.0, size=(n_cells_per_type, n_markers)
        ).astype(np.float32)

    counts = np.log1p(counts)

    obs = pd.DataFrame(
        {
            "celltype":    labels,
            "class_label": [class_map[ct] for ct in labels],
        },
        index=[f"cell_{i}" for i in range(n_cells)],
    )
    var = pd.DataFrame(index=[f"gene_{i}" for i in range(n_genes)])
    return ad.AnnData(X=scipy.sparse.csr_matrix(counts), obs=obs, var=var)


@pytest.fixture(scope="session")
def small_adata() -> ad.AnnData:
    """Tiny synthetic AnnData (150 cells × 200 genes) for fast unit tests.

    Does not require any reference data files.  Used for shape/contract tests
    that don't need R comparison.

    Structure: 3 cell types (50 cells each), each with 20 marker genes.
    Marker genes are interleaved (genes 0,3,6,...: TypeA; 1,4,7,...: TypeB;
    2,5,8,...: TypeC) so that any contiguous slice of 10+ genes contains
    informative markers for all 3 cell types.  This ensures tests using
    ``var_names[:N]`` get a well-balanced panel.
    """
    rng = np.random.default_rng(42)
    n_cells_per_type = 50
    n_genes = 200
    n_marker = 20   # marker genes per cell type
    n_types = 3

    cell_types = ["TypeA", "TypeB", "TypeC"]
    labels = np.repeat(cell_types, n_cells_per_type)
    n_cells = n_cells_per_type * n_types

    # Background: low Poisson expression for all genes/cells
    counts = rng.poisson(lam=0.5, size=(n_cells, n_genes)).astype(np.float32)

    # Interleaved marker gene indices: type t gets genes t, t+3, t+6, ...
    # Markers have decreasing lambda (8.0 → 4.0) so the greedy algorithm has
    # a clear preference ordering within each cell type, making exact/approx
    # results more consistent with each other.
    for t, ct in enumerate(cell_types):
        marker_cols = list(range(t, t + n_marker * n_types, n_types))  # n_marker indices
        cell_rows = np.where(labels == ct)[0]
        lams = np.linspace(8.0, 4.0, n_marker)
        for j, col in enumerate(marker_cols):
            counts[np.ix_(cell_rows, [col])] = (
                rng.poisson(lam=lams[j], size=(n_cells_per_type, 1)).astype(np.float32)
            )

    counts = np.log1p(counts)

    obs = pd.DataFrame(
        {
            "celltype": labels,
            "batch": rng.choice(["batch1", "batch2"], size=n_cells),
        },
        index=[f"cell_{i}" for i in range(n_cells)],
    )
    var = pd.DataFrame(index=[f"gene_{i}" for i in range(n_genes)])
    return ad.AnnData(X=scipy.sparse.csr_matrix(counts), obs=obs, var=var)
